STATUS_DEFAULT = 0 #False

STATUS_OFF = 2

USER_EXTENSION_USING_VERIFIED = 1010
USER_EXTENSION_USING_UNVERIFIED = 1020
USER_EXTENSION_USING_UNDER_30DAYS_VERIFIED = 1021
USER_EXTENSION_USING_UNDER_30DAYS_UNVERIFIED = 1023

